#!/usr/bin/python
import logging

_LOGGING_MAP = {
    "debug": logging.DEBUG,
    "info": logging.INFO,
    "error": logging.ERROR,
    "critical": logging.CRITICAL,
}
_KEEP_ALIVE_INTERVAL = 20000 #milliseconds
_RETRY_INTERVAL = 5000
_CONNECTION_APPROVAL_INTERVAL = 10000
_RETRY_COUNT = 5
_LENGTH_LENGTH = 4
_CID_LENGTH = 4
_FLAG_LENGTH = 1
_SQN_LENGTH = 2
_DATA_LENGTH = 1024
_MAX_INIT_LENGTH = 43
_HTTP_PORT = 80
_RUDP_PORT = 1026
_CONTROL_PORT = 1025
_TIMEOUT = 2000
_HTTP_BUFF_LIMIT = 4096
_HTTP_BLOCK_SIZE = 1024
_CONTROL_BUFF_LIMIT = 4096
_CONTROL_BLOCK_SIZE = 1024
_FILE_BLOCK_SIZE = 1024
_DATA_BUFF_LIMIT = 4096
_DATA_BLOCK_SIZE = 1024
_MAX_RUDP_SIZE = _DATA_LENGTH + _SQN_LENGTH + _FLAG_LENGTH + _CID_LENGTH + _LENGTH_LENGTH
_MAX_CONNECTIONS = 1
_CONTROL_OK = 0
_CONTROL_INVALID_REQUEST = 1
_CONTROL_TOO_MANY_CONNECTIONS = 2
_CONTROL_CONNECTION_NOT_EXIST = 3
_LF = '\n'
_LF_BIN = _LF.encode('utf-8')
_CRLF = '\r\n'
_CRLF_BIN = _CRLF.encode('utf-8')
_HTTP_SIGNATURE = 'HTTP/1.1'
_MAX_HEADER_LENGTH = 4096
_MAX_NUMBER_OF_HEADERS = 100
_HTTP_INTERNAL_ERROR = 500
_HTTP_FILE_NOT_FOUND = 404
_HTTP_OK_CODE = 200
_HTTP_OK_MESSAGE = "OK"
_BASE_DIRECTORY = "."
_MIN_PORT = 0
_MAX_PORT = 65536
_CONTENT_TYPES = {
    '.css': 'text/css',
    '.html': 'text/html',
    '.txt': 'text/plain',
    '.ico': 'image/x-icon',
}
_STD_OUT = 1
